default_stages: [commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: check-json # Attempts to load all json files to verify syntax
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-case-conflict # Check for files with names that would conflict on a case-insensitive filesystem like MacOS HFS+ or Windows FAT.
      - id: check-merge-conflict # Check for files that contain merge conflict strings

  - repo: local
    hooks:
      - id: tb-fmt
        name: tb fmt
        entry:  make format
        language: system
        pass_filenames: false
        stages: [push]